services:
  data_ingestion:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash_node01
    hostname: logstash_node01
    volumes:
      - ./logstash/pipeline.conf:/config/pipeline.conf
    ports:
      - "5000:5000" # tcp input
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g # jvm heap tuning
      - XPACK_MONITORING_ENABLED=false
      - XPACK_MANAGEMENT_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    networks:
      - hermes-network
    command: logstash -f /config/pipeline.conf

  data_streaming:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://kafka:9092,PLAINTEXT://kafka:29092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    networks:
      - hermes-network

  topics: # container di supporto per creare i topic (init container pattern), oppure crearlo da cli nel container "kafka"
    image: apache/kafka:latest
    hostname: kafka_topics
    container_name: kafka_topics
    command: >
      bash -c "
      /opt/kafka/bin/kafka-topics.sh \
      --create \
      --topic email.raw \
      --bootstrap-server kafka:9092 \
      --if-not-exists &&
      /opt/kafka/bin/kafka-topics.sh \
      --create \
      --topic email.predictions \
      --bootstrap-server kafka:9092 \
      --if-not-exists &&
      /opt/kafka/bin/kafka-topics.sh \
      --create \
      --topic url.deep_analysis \
      --bootstrap-server kafka:9092 \
      --if-not-exists
      "
    depends_on:
      - data_streaming
    networks:
      - hermes-network # gli serve per fare dns resolve di "kafka"

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    ports:
      - "8081:8080" # web ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=hermes_email_security
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - hermes-network
    depends_on:
      - data_streaming

  data_processing:
    # image: apache/spark:3.5.0 # è la versione LTS
    build: ./spark_processing
    container_name: spark
    hostname: spark
    ports:
      - "8082:8080" # web ui
      - "7077:7077" # master comm port
    volumes: # mappare codice pyspark in /code/processing.py e modelli ML
      - ./spark_processing/:/code/spark_processing/
    command: > # tutto su una riga sennò si rompe il parsing
      bash -c '/opt/spark/bin/spark-submit --conf spark.driver.extraJavaOptions="-Divy.cache.dir=/tmp -Divy.home=/tmp" --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 /code/spark_processing/processing.py'
    depends_on:
      topics:
        condition: service_completed_successfully # creiamo prima i topic kafka
    networks:
      - hermes-network

  url_extractor:
    # image: apache/spark:3.5.0 # è la versione LTS
    build: ./spark_processing
    container_name: url_extractor
    hostname: url_extractor
    ports:
      # - "8082:8080" # web ui
      - "7078:7077" # master comm port
    volumes:
      - ./spark_processing/:/code/spark_processing/
    environment:
      - SPARK_LOCAL_HOSTNAME=localhost

    command: > # tutto su una riga sennò si rompe il parsing
      bash -c '/opt/spark/bin/spark-submit --conf spark.driver.extraJavaOptions="-Divy.cache.dir=/tmp -Divy.home=/tmp" --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 /code/spark_processing/url_extractor.py'
    depends_on:
      topics:
        condition: service_completed_successfully # creiamo prima i topic kafka
    networks:
      - hermes-network


  url_service:
    build:
      context: ./url_service
    container_name: url_service
    hostname: url_service
    restart: unless-stopped
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      INPUT_TOPIC: url.to_analyze
      OUTPUT_TOPIC: url.deep_analysis
      GROUP_ID: url-service-group
    depends_on:
      - data_streaming
      - url_extractor
    networks:
      - hermes-network

  catchmail_poll:
    build:
      context: ./catchmail_poll
    container_name: catchmail_poll
    hostname: catchmail_poll
    restart: unless-stopped
    depends_on:
      - data_ingestion
      - data_processing
      - data_streaming
    networks:
      - hermes-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 1 GB
    ports:
      - "9200:9200"
    networks:
      - hermes-network

      
  ingestion-kafka-to-es:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash_node02
    hostname: logstash_node02
    volumes:
      - ./logstash/kafka_to_es.conf:/config/kafka_to_es.conf
    environment:
      - LS_JAVA_OPTS=-Xms4g -Xmx4g # jvm heap tuning
      - XPACK_MONITORING_ENABLED=false
      - XPACK_MANAGEMENT_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    networks:
      - hermes-network
    command: logstash -f /config/kafka_to_es.conf
    depends_on:
      - elasticsearch
      - data_streaming

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - hermes-network

networks:
  hermes-network:
    driver: bridge



